[build]
  command = "npm install && npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  NETLIFY_IMAGE_CDN_DOMAIN = "imgix.net"
  NODE_OPTIONS = "--openssl-legacy-provider"
  VITE_APP_ENV = "production"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Static assets handling with proper caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image optimization
[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:;"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:;"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"
    Access-Control-Allow-Origin = "*"

# Images handling
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"
    Content-Type = "image/png"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"
    Content-Type = "image/jpeg"
